backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  api_root: "https://api.github.com"
  site_domain: "gregarious-chaja-569265.netlify.app"
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}_{month}_{day}_{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: "{{year}/{month}/{day}}"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Type", name: "type", widget: "string", hidden: true, default: "blank"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Series", name: "series", widget: "list", required: false}
      - {label: "Aliases", name: "aliases", widget: "list", required: false}
      - {label: "Content", name: "content", widget: "markdown"}

